/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package edu.cotarelo.sistema;

import edu.cotarelo.dao.factories.MySQLFactory;
import edu.cotarelo.dao.objects.UsuarioDAO;
import edu.cotarelo.domain.Usuario;
import java.awt.Color;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.naming.NamingException;
import javax.swing.JOptionPane;

/**
 * Clase para presentar la pantalla de login
 *
 * @author desarotti
 */
public class Login extends javax.swing.JFrame {

    /**
     * Creates new form Login
     */
    public Login() {
        initComponents();
    }

    /**
     * Comprueba que la combinación de usuario y contraseña escrita en los
     * campos de texto sea válida y se corresponda con un usuario de la base de
     * datos.
     * @return Un usuario si la validación es correcta, null en caso contrario.
     */
    private Usuario validarUsuario() {
        Usuario usuario = null;
        if (!loginNombre.getText().isBlank()
                && !loginNombre.getText().equals("Introduzca aquí su nombre de usuario")
                && !loginPass.getText().isBlank()) {
            try {
                String usuarioNombre = loginNombre.getText();
                String pass = loginPass.getText();
                MySQLFactory f = new MySQLFactory();
                UsuarioDAO usuarioDao = f.getUsuarioDAO();
                usuario = usuarioDao.getUsuarioByNombreContraseña(usuarioNombre, pass);
                if (usuario == null) {
                    JOptionPane.showMessageDialog(null, "Usuario o contraseña incorrectos");
                } else {
                    JOptionPane.showMessageDialog(null, "Usuario Autenticado!");
                }
            } catch (NamingException ex) {
                Logger.getLogger(Login.class.getName()).log(Level.SEVERE, null, ex);
            }
        } else {
            JOptionPane.showMessageDialog(null, "Debe introducir el usuario y la contraseña");
        }
        return usuario;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        loginTitulo = new javax.swing.JLabel();
        loginNombreTitulo = new javax.swing.JLabel();
        loginNombre = new javax.swing.JTextField();
        loginPassTitulo = new javax.swing.JLabel();
        loginPass = new javax.swing.JTextField();
        balonAzul = new javax.swing.JLabel();
        loginButton = new javax.swing.JButton();
        cesped = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        loginTitulo.setFont(new java.awt.Font("Segoe UI", 1, 36)); // NOI18N
        loginTitulo.setForeground(new java.awt.Color(0, 0, 102));
        loginTitulo.setText("Acceso para usuarios");
        getContentPane().add(loginTitulo, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 80, -1, -1));

        loginNombreTitulo.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        loginNombreTitulo.setForeground(new java.awt.Color(0, 0, 204));
        loginNombreTitulo.setText("NOMBRE");
        getContentPane().add(loginNombreTitulo, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 250, -1, -1));

        loginNombre.setBackground(new java.awt.Color(0, 204, 0));
        loginNombre.setForeground(new java.awt.Color(255, 255, 255));
        loginNombre.setText("Introduzca aquí su nombre de usuario");
        loginNombre.setBorder(null);
        loginNombre.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                loginNombreFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                loginNombreFocusLost(evt);
            }
        });
        loginNombre.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                loginNombreActionPerformed(evt);
            }
        });
        getContentPane().add(loginNombre, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 280, 390, 40));

        loginPassTitulo.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        loginPassTitulo.setForeground(new java.awt.Color(0, 0, 204));
        loginPassTitulo.setText("CONTRASEÑA");
        getContentPane().add(loginPassTitulo, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 350, -1, -1));

        loginPass.setBackground(new java.awt.Color(0, 204, 0));
        loginPass.setForeground(new java.awt.Color(255, 255, 255));
        loginPass.setText("Introduzca aquí su contraseña");
        loginPass.setBorder(null);
        loginPass.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                loginPassFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                loginPassFocusLost(evt);
            }
        });
        loginPass.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                loginPassActionPerformed(evt);
            }
        });
        getContentPane().add(loginPass, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 380, 390, 40));

        balonAzul.setIcon(new javax.swing.ImageIcon(getClass().getResource("/edu/cotarelo/img/balon_azul.png"))); // NOI18N
        getContentPane().add(balonAzul, new org.netbeans.lib.awtextra.AbsoluteConstraints(500, 30, 150, 150));

        loginButton.setBackground(new java.awt.Color(51, 51, 255));
        loginButton.setFont(new java.awt.Font("Segoe UI", 1, 36)); // NOI18N
        loginButton.setForeground(new java.awt.Color(255, 255, 255));
        loginButton.setText("Iniciar");
        loginButton.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                loginButtonMouseClicked(evt);
            }
        });
        loginButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                loginButtonActionPerformed(evt);
            }
        });
        getContentPane().add(loginButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 460, 200, 70));

        cesped.setIcon(new javax.swing.ImageIcon(getClass().getResource("/edu/cotarelo/img/cesped.jpeg"))); // NOI18N
        getContentPane().add(cesped, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 680, 570));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void loginNombreActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_loginNombreActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_loginNombreActionPerformed

    private void loginPassActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_loginPassActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_loginPassActionPerformed

    private void loginNombreFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_loginNombreFocusGained
        if (loginNombre.getText().equals("Introduzca aquí su nombre de usuario")) {
            loginNombre.setText("");
            loginNombre.setForeground(Color.BLACK);
        }
    }//GEN-LAST:event_loginNombreFocusGained

    private void loginNombreFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_loginNombreFocusLost
        if (loginNombre.getText().equals("")) {
            loginNombre.setText("Introduzca aquí su nombre de usuario");
            loginNombre.setForeground(Color.WHITE);
        }
    }//GEN-LAST:event_loginNombreFocusLost

    private void loginPassFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_loginPassFocusGained
        if (loginPass.getText().equals("Introduzca aquí su contraseña")) {
            loginPass.setText("");
            loginPass.setForeground(Color.BLACK);
        }
    }//GEN-LAST:event_loginPassFocusGained

    private void loginPassFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_loginPassFocusLost
        if (loginPass.getText().equals("")) {
            loginPass.setText("Introduzca aquí su contraseña");
            loginPass.setForeground(Color.WHITE);
        }
    }//GEN-LAST:event_loginPassFocusLost

    private void loginButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_loginButtonActionPerformed
        // TODO add your handling code here:
        Usuario usuario = validarUsuario();
        if (usuario != null) {
            new Sistema(usuario).setVisible(true);
            setVisible(false);
        }
    }//GEN-LAST:event_loginButtonActionPerformed

    private void loginButtonMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_loginButtonMouseClicked
        
    }//GEN-LAST:event_loginButtonMouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Login().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel balonAzul;
    private javax.swing.JLabel cesped;
    private javax.swing.JButton loginButton;
    private javax.swing.JTextField loginNombre;
    private javax.swing.JLabel loginNombreTitulo;
    private javax.swing.JTextField loginPass;
    private javax.swing.JLabel loginPassTitulo;
    private javax.swing.JLabel loginTitulo;
    // End of variables declaration//GEN-END:variables
}
